User.create!([
  {email: "stefbward@gmail.com", encrypted_password: "$2a$11$eYxcJJ.8uHjvaSjRExRi3.phtp3/iFcUYNYiTW9JiY9q5mQiI38Qy", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 5, current_sign_in_at: "2016-08-30 12:42:46", last_sign_in_at: "2016-08-30 11:47:01", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", username: "Stefanie", bio: ""},
  {email: "arturogcaesar@gmail.com", encrypted_password: "$2a$11$vvpL6mfHzcLzMlP0v8pclOxvHlyTT4sFzcWVHhnZITsaGLWwajPcG", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2016-08-30 13:31:30", last_sign_in_at: "2016-08-29 17:43:41", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", username: "", bio: ""},
  {email: "palakunc@gmail.com", encrypted_password: "$2a$11$V/eJOzw229DxK.cbOCQe9.zOqs05TxPyEpb4MCZ4jSndHzNrh0toe", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 4, current_sign_in_at: "2016-08-30 13:44:49", last_sign_in_at: "2016-08-30 13:23:14", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", username: "", bio: ""}
])
Attraction.create!([
  {name: "Tower of London", destination_id: 2, description: "Founded by William the Conqueror in 1066, and enlarged and modified by successive sovereigns, the Tower is today one of the world's most famous and spectacular fortresses.", hours: "Tue - Sat: 9:00 AM - 4:30 PM; Sun - Mon 10:00 AM - 4:30 PM. Open till 5:30 PM March 1 - October 31.", cost: "£9.50 (Children, purchased online) to £22.50 (Adult, purchased at the gate). Family, student, senior discounts available."},
  {name: "City Hall Station", destination_id: 3, description: "The first NYC subway was built and operated by the Interborough Rapid Transit Company (IRT) and opened on October 27, 1904, to the joy of New York elevated train riders. In 1940, the IRT became the IRT Division after it was integrated with the city-owned New York Subway system. ", hours: "Check with Museum", cost: "Free with Museum Admission"},
  {name: "Taj Mahal", destination_id: 1, description: "The Taj Mahal is an ivory-white marble mausoleum on the south bank of the Yamuna river in the Indian city of Agra. It was commissioned in 1632 by the Mughal emperor, Shah Jahan, to house the tomb of his favourite wife, Mumtaz Mahal", hours: "N/A", cost: "Cost: Rs. 1000 ($14.92)"},
  {name: "Red Fort", destination_id: 1, description: "The Red Fort was the residence of the Mughal emperor for nearly 200 years, until 1857. It is located in the centre ofDelhi and houses a number of museums.", hours: "Hours: Sunrise - Sunset", cost: "Rs. 550 (USD $8.20)"},
  {name: "Gateway of India", destination_id: 4, description: "The Gateway of India was built to commemorate the visit of King George V and Queen Mary to Mumbai, prior to the Delhi Durbar, in December 1911. It is known as the official welcoming site into the country.", hours: "Hours: 24/7 – Best around nighttime with less visitors!", cost: "Free"},
  {name: "Jaisalmer Fort", destination_id: 6, description: "Built in 1156 AD, the Jaisalmer Fort is one of the largest fortifications on the world. The fort stands amidst the sandy expanse of the great Thar Desert, on Trikuta Hill, and has been the scene of many battles.", hours: "9am - 5pm", cost: "Free"},
  {name: "Adalaj Stepwell", destination_id: 5, description: "Mahmud Begada built the Adalaj Stepwelll in 1499 for his queen Rudabai, wife of Veersinh, the Vaghela chieftain. Such step wells were once integral to the semi-arid regions of Gujarat, as they provided water for drinking, washing and bathing. These wells were also venues for colourful festivals and sacred rituals.", hours: "24/7", cost: "Free"},
  {name: "Roosevelt Island Smallpox Hospital Ruins", destination_id: 3, description: "Crumbling hospital from 1850s on Roosevelt Island. ", hours: "N/A", cost: "Suggested $1 Donation"},
  {name: "Please Don't Tell", destination_id: 3, description: "If you can get over your self-consciousness, and the line isn't unbearable, PDT is a pretty cool experience. Enter the phone booth at the side of the restaurant, and wait, assuming you get through, because the coolest part of the experience is just seconds away.", hours: "6PM - 2AM", cost: "N/A"},
  {name: "Lower East Side Toy Company(The Back Room)", destination_id: 3, description: "Through the gate that reads \"Lower East Side Toy Company\" make your way along an historic path to the Back Room, a true-to-life 1920s era speakeasy.", hours: "7:30PM - 3:00AM", cost: "N/A"},
  {name: "Gold Bar", destination_id: nil, description: "With tables custom-made to look like Cartier bracelets, everything is designed to be a constant reminder of the glamorous elitism that patrons get to be a part of.", hours: "11PM - 4AM", cost: "$$$$"},
  {name: "Gold Bar", destination_id: 3, description: "With tables custom-made to look like Cartier bracelets, everything is designed to be a constant reminder of the glamorous elitism that patrons get to be a part of.", hours: "11PM - 4AM", cost: "$$$$"},
  {name: "British Museum", destination_id: 2, description: "A vast repository of the world's cultures, with entire sections devoted to Egyptian, Greek, and Middle Eastern artifacts, as well as the piece which united them all, the Rosetta Stone.", hours: "Sat-Wed 10:00 AM - 5:30 PM, Thu-Fri 10:00 AM - 8:30 PM", cost: "Free (suggested donation £3)"},
  {name: "Globe Theater", destination_id: 2, description: "Sam Wanamaker's largely authentic reconstruction of Shakespeare's Globe Theatre, built using traditional techniques, stages plays in the Summer months.", hours: "Vary by performance", cost: "£5 - £45 per ticket"}
])
Destination.create!([
  {name: "Agra, Uttar Pradesh, India", image_file_name: "agra-india-architecture.jpg", image_content_type: "image/jpeg", image_file_size: 370664, image_updated_at: "2016-08-30 12:54:12"},
  {name: "London, England, UK", image_file_name: "london.jpg", image_content_type: "image/jpeg", image_file_size: 724897, image_updated_at: "2016-08-30 12:57:51"},
  {name: "New York City, NY, USA", image_file_name: "nyc.jpg", image_content_type: "image/jpeg", image_file_size: 516107, image_updated_at: "2016-08-30 12:58:06"},
  {name: "Mumbai, Maharashtra, India", image_file_name: "in_Gateway-of-India_2014_02.jpg", image_content_type: "image/jpeg", image_file_size: 475237, image_updated_at: "2016-08-30 13:25:58"},
  {name: "Adalaj, Gujarat, India", image_file_name: "Adalaj_step_well.jpg", image_content_type: "image/jpeg", image_file_size: 79565, image_updated_at: "2016-08-30 13:28:55"},
  {name: "Jaisalmer, Rajasthan, India", image_file_name: "Jaisalmer-Fort.jpg", image_content_type: "image/jpeg", image_file_size: 150864, image_updated_at: "2016-08-30 13:29:39"}
])
Review.create!([
  {title: "History of London", content: "The Tower of London was one of the serious highlights of my time in the city. Yes, it's a conventional touristy thing to do, but it's a great slice of London history since the Norman Conquest. Plus, a lot of different things to do.", attraction_id: 1, user_id: 1, destination_id: nil, image_file_name: "IMG_1667.jpg", image_content_type: "image/jpeg", image_file_size: 4706479, image_updated_at: "2016-08-29 20:02:33", rating: 5},
  {title: "Creepy Place", content: "This is quite possibly the most haunting place in NYC. This dilapidated hospital once treated 7,000 patients annually and roughly 450 would die each year. Over its 30 year history about 13,500 patients have died. There were strange sounds echoing throughout the halls and even dark shadows that seem to watch you from behind the looming walls. If you're interested in a supernatural experience filled with history, then you're in for a trip of a lifetime.", attraction_id: 8, user_id: 2, destination_id: nil, image_file_name: "renwick.jpg", image_content_type: "image/jpeg", image_file_size: 102069, image_updated_at: "2016-08-30 13:44:34", rating: 4},
  {title: "The view was free, but almost falling? Priceless!", content: "This step well is absolutely gorgeous! The details along the wall are so intricate and make for great photos. I was able to climb all the way down and see the stepwell from the bottom, which was beautiful. My only reason for the mediocre rating is that I almost fell in! There are no barriers to prevent you from falling in, so BE CAREFUL!", attraction_id: 7, user_id: 3, destination_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, rating: 3}
])
